name: Cypress DemoQA Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_REPORTER: mochawesome

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress DemoQA tests

        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          reporter: ${{ env.CYPRESS_REPORTER }}
